name: Lint and Prettier

on:
  push:
    branches: [main]

jobs:
  lint-prettier-test:
    name: Apply lint and prettier
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node.js v16
        uses: actions/setup-node@v3
        with:
          node-version: "16"
      - name: Install dependencies
        run: npm ci
      - name: Prettier
        run: npm run format
      - name: Lint
        run: npm run lint
